#browser options: chrome , firefox
#testdata options: test1, test2

defaultBrowser: chrome
defaultEnvironment: test2

testData:
  test1:
    envName: test2
    appUrl: https://seleniumui.moderntester.pl/form.php
    firstName: Lars
    lastName: Ulrich
    email: lars@drums.com
    age: 45
    additional: 1234 1234
    message: Form send with success
    filepath: src/main/resources/file.txt

  test2:
    envName: test2
    appUrl: https://seleniumui.moderntester.pl/form.php
    firstName: Lars
    lastName: Ulrich
    email: lars@drums.com
    age: 45
    additional: 1234 1234
    message: Form send with success
    filepath: src/main/resources/file.txt

---